/* eslint-env jest */

jest.mock('react-native-config', () => ({
  LOGGYM_GOOGLE_WEB_CLIENT_ID: '',
  LOGGYM_GOOGLE_IOS_CLIENT_ID: '',
  LOGGYM_ENABLE_DEV_LOGIN: 'true',
  LOGGYM_FIREBASE_USE_EMULATORS: 'false',
  LOGGYM_FIREBASE_AUTH_EMULATOR_HOST: '',
  LOGGYM_FIREBASE_FIRESTORE_EMULATOR_HOST: '',
}));
